check-location:
  world: world
  x: 0.0
  y: 64.0
  z: 0.0

allowed-commands:
  - m
  - msg
  - r

release-command: "spawn {player}"

messages:
  player-not-found: "§6Проверка §7» §cИгрок не найден§7."
  player-teleported: "§6Проверка §7» §fИгрок §6{player} §fтелепортирован в место проверки§7."
  player-released: "§6Проверка §7» §fИгрок §6{player} §fосвобожден от проверки§7."
  player-not-under-check: "§6Проверка §7» §cИгрок §6{player} §cне находится на проверки§7."
  invalid-command-usage: "§6Проверка §7» §cНеверное использование команды§7."
  command-not-allowed: "§cВам не разрешено использовать эту команду во время проверки!"
  move-not-allowed: "§cВы не можете двигаться§7, §cнаходясь на проверки!"
  drop-not-allowed: "§cВы не можете выбрасывать предметы§7, §cнаходясь на проверки!"
  interact-not-allowed: "§cВы не можете взаимодействовать с блоками§7, §cнаходясь на проверки!"
  config-reloaded: "§6Проверка §7» §aКонфигурация перезагружена!"
  no-permission: "§6Проверка §7» §cУ вас нет разрешения на использование этой команды§7."
  check-title: "§cПРОВЕРКА ЧЕРЕЗ ANYDESK"
  check-subtitle: "§fВсе инструкции находятсяв чате."
  check-message: "§4§lВНИМАНИЕ §cВы были вызваны на проверку через §4AnyDesk\n§f\n§cИнструкция§7: §fhttps://reallyworld.me/anydesk\n§f\n§fПишите свой код доступа §4AnyDesk §fв чат§7. §cУ вас есть 5 минут\n§fЕсли у вас мут используйте §c/msg [ник модера] сообщение\n§f\n§fПризнание в использовании читов §7- §c46 дней бана\n§fЗа выход с сервера во время проверки §7- §c50 дней бана\n§f\n§cВажно§7: §fПроверяющему запрещено вводить различные команды для ПК §7(powershell, cmd), §fа так же совершать действия§7, §fкоторые не касаются проверки (отвязка аккаунта и тому подобное)§7.\n§f\n§cУвидели нарушение со стороны модератора§7, §cфиксируйте это и сообщайте нам об этом на форум§7: §chttps://f.reallyworld.ru\n§f\n§f"
  message-sent-to-moderator: "§7Ваше сообщение отправлено модератору."
  message-from-player: "§fСообщение от §6{player}§7: §c{message}"