check-location: # Место куда будет телепортирован игрок
  world: world
  x: 0.0
  y: 64.0
  z: 0.0

allowed-commands: # Команды которые разрешины во время проверки
  - m
  - msg
  - r

release-command: "spawn {player}" # Команда когда игрок прошол проверку

settings:
  command-on-check-leave: "tempban {player} 50d Лив с проверки!" # Команды когда игрок выходит с сервера во время проверки

messages: # Всё сообщение плагина настройка под rw
  player-not-found: "§6Проверка §7» §cИгрок не найден§7."
  player-teleported: "§6Проверка §7» §fИгрок §6{player} §fтелепортирован в место проверки§7."
  player-released: "§6Проверка §7» §fИгрок §6{player} §fосвобожден от проверки§7."
  player-not-under-check: "§6Проверка §7» §cИгрок §6{player} §cне находится на проверки§7."
  invalid-command-usage: "§6Проверка §7» §cНеверное использование команды§7."
  command-not-allowed: "§cВам не разрешено использовать эту команду во время проверки!"
  config-reloaded: "§6Проверка §7» §aКонфигурация перезагружена!"
  no-permission: "§6Проверка §7» §cУ вас нет разрешения на использование этой команды§7."
  check-title: "§cПРОВЕРКА ЧЕРЕЗ ANYDESK"
  check-subtitle: "§fВсе инструкции находятсяв чате."
  check-message: "§4§lВНИМАНИЕ §7Вы были вызваны на проверку через §4§lAnyDesk\n§7\n§7Инструкция: §chttps://reallyworld.me/anydesk\n§7\n§cПишите свой код доступа AnyDesk в чат §7У вас есть 5 минут\n§7Если у вас мут используйте §6/mod сообщение\n§7\n§7Признание в использовании читов - §c46 дней бана\n§7За выход с сервера во время проверки - §c50 дней бана\n§7\n§7Важно: Проверяющему запрещено вводить различные\n§7 команды для ПК (powershell, cmd), а так же совершать\n§7 действия, которые не касаются проверки (отвязка аккаунта\n§7 и тому подобное).\n§7\n§7Увидели нарушение со стороны модератора, фиксируйте это\n§7 и сообщайте нам об этом на форум: §chttps://f.reallyworld.me/"
  message-sent-to-moderator: "§7Ваше сообщение отправлено модератору."
  message-from-player: "§fСообщение от §6{player}§7: §c{message}"
  player-left-during-check: "§6Проверка §7» §cИгрок §6{player} §cвышел во время проверки!"