name: AnCheck
main: com.github.AnCheckPlugin
version: 1.2
api-version: 1.16
commands:
  check:
    description: Проверка игрока на наличие читов, отмена проверки или перезагрузка конфигурации.
    usage: "§6Проверка §7» §f/check §7[§fник игрок§7] §6или §f/check off §7[§fник игрок§7] §6или §f/check reload"
    permission: ancheckplugin.check
permissions:
  ancheckplugin.check:
    description: Позволяет использовать команду /check.
    default: op
  ancheckplugin.reload:
    description: Позволяет использовать команду /check reload.
    default: op
  ancheckplugin.moderator:
    description: Позволяет игроку получать сообщения, отправленные игроками, находящимися под контролем.
    default: op